language: java
jdk: oraclejdk8
after_success:
- ./upload.sh
before_install:
- '[ "$TRAVIS_PULL_REQUEST" == "false" ] && openssl aes-256-cbc -K $encrypted_9571655a8072_key -iv $encrypted_9571655a8072_iv -in secring.gpg.enc -out secring.gpg -d || echo "no decryption for pull requests"'
